export const CHANGE_LOCALE = 'CHANGE_LOCALE'
export const LOG_OUT = 'LOG_OUT'

/**
 * --------------------------------
 * Redux: currentUser
 * --------------------------------
 */
export const LOADING_IN_USER = 'LOADING_IN_USER'
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS'
export const GET_CURRENT_USER_FAILURE = 'GET_CURRENT_USER_FAILURE'

/**
 * --------------------------------
 * Home
 * --------------------------------
 */
export const VERIFY_SUBDOMAIN = 'VERIFY_SUBDOMAIN'
export const VERIFY_SUBDOMAIN_SUCCESS = 'VERIFY_SUBDOMAIN_SUCCESS'
export const VERIFY_SUBDOMAIN_FAILED = 'VERIFY_SUBDOMAIN_FAILED'
export const VERIFY_REGISTER_LINK_SAGA = 'VERIFY_REGISTER_LINK_SAGA'
export const VERIFY_REGISTER_LINK_SUCCESS = 'VERIFY_REGISTER_LINK_SUCCESS'
export const REGISTER_LINK_SAGA = 'REGISTER_LINK_SAGA'
export const AUTHORIZED_SUCCESS = 'AUTHORIZED_SUCCESS'
export const UPDATE_PROFILE_REQUEST = 'UPDATE_PROFILE_REQUEST'
export const UPDATE_PROFILE_SUCCESS = 'UPDATE_PROFILE_SUCCESS'
export const CHECK_TOKEN = 'CHECK_TOKEN'
export const CHECK_TOKEN_FAILED = 'CHECK_TOKEN_FAILED'
export const CHECK_TOKEN_SUCCESS = 'CHECK_TOKEN_SUCCESS'
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'
export const SET_NEW_PASSWORD_REQUEST = 'SET_NEW_PASSWORD_REQUEST'
export const SET_NEW_PASSWORD_SUCCESS = 'SET_NEW_PASSWORD_SUCCESS'
export const SET_NEW_PASSWORD_FAILURE = 'SET_NEW_PASSWORD_FAILURE'
export const VERIFY_USER = 'VERIFY_USER'
export const VERIFY_USER_SUCCESS = 'VERIFY_USER_SUCCESS'
export const VERIFY_USER_FAILED = 'VERIFY_USER_FAILED'
export const SET_USER_PROP = 'SET_USER_PROP'
export const SET_OTHER_USER_PROP = 'SET_OTHER_USER_PROP'
export const CHECK_USER = 'CHECK_USER'
export const CHECK_USER_SUCCEED = 'CHECK_USER_SUCCEED'
export const CHECK_USER_FAILED = 'CHECK_USER_FAILED'
export const GET_USER_INFO = 'GET_USER_INFO'
export const GET_USER_INFO_SAGA = 'GET_USER_INFO_SAGA'
export const GET_USER_INFO_FAIL = 'FAIL_OTHERUSER'
export const GET_USER_INFO_SUCCESS = 'GET_USER_INFO_SUCCESS'


/**
 * Dashboard
 */
export const LOADING_ALL_FEEDBACK = 'LOADING_ALL_FEEDBACK'
export const FETCH_ALL_FEEDBACK_SAGA = 'FETCH_ALL_FEEDBACK_SAGA'
export const FETCH_ALL_FEEDBACK_SUCCESS = 'FETCH_ALL_FEEDBACK_SUCCESS'
export const FETCH_ALL_FEEDBACK_FAILURE = 'FETCH_ALL_FEEDBACK_FAILURE'

/**
 * Members
 */
export const GET_COMPANY_MEMBERS_LOADING = 'GET_COMPANY_MEMBERS_LOADING'

export const GET_COMPANY_MEMBERS_SAGA = 'GET_COMPANY_MEMBERS_SAGA'
export const GET_COMPANY_MEMBERS_SUCCESS = 'GET_COMPANY_MEMBERS_SUCCESS'
export const GET_COMPANY_MEMBERS_FAILURE = 'GET_COMPANY_MEMBERS_FAILURE'

export const GET_INVITE_LINK_SAGA = 'GET_INVITE_LINK_SAGA'
export const GET_INVITE_LINK_SUCCESS = 'GET_INVITE_LINK_SUCCESS'
export const GET_INVITE_LINK_FAILURE = 'GET_INVITE_LINK_FAILURE'

export const UPGRADE_ADMIN_SAGA = 'UPGRADE_ADMIN_SAGA'
export const UPGRADE_ADMIN_SUCCESS = 'UPGRADE_ADMIN_SUCCESS'
export const UPGRADE_ADMIN_FAILURE = 'UPGRADE_ADMIN_FAILURE'

export const UPGRADE_OWNER_SAGA = 'UPGRADE_OWNER_SAGA'
export const UPGRADE_OWNER_SUCCESS = 'UPGRADE_OWNER_SUCCESS'
export const UPGRADE_OWNER_FAILURE = 'UPGRADE_OWNER_FAILURE'

export const DOWNGRADE_USER_SAGA = 'DOWNGRADE_USER_SAGA'
export const DOWNGRADE_USER_SUCCESS = 'DOWNGRADE_USER_SUCCESS'
export const DOWNGRADE_USER_FAILURE = 'DOWNGRADE_USER_FAILURE'

export const DELETE_MEMBER_SAGA = 'DELETE_MEMBER_SAGA'
export const DELETE_MEMBER_SUCCESS = 'DELETE_MEMBER_SUCCESS'
export const DELETE_MEMBER_FAILURE = 'DELETE_MEMBER_FAILURE'

export const INVITE_MEMBERS_SAGA = 'INVITE_MEMBERS_SAGA'
export const INVITE_MEMBERS_SUCCESS = 'INVITE_MEMBERS_SUCCESS'
export const INVITE_MEMBERS_FAILURE = 'INVITE_MEMBERS_FAILURE'

export const REINVITE_MEMBERS_SUCCESS = 'REINVITE_MEMBERS_SUCCESS'
export const REINVITE_MEMBERS_FAILURE = 'REINVITE_MEMBERS_FAILURE'


export const LOADING_SUCCESS_FIRST = 'LOADING_SUCCESS_FIRST'
export const REDIRECT_URL = 'REDIRECT_URL'
export const GET_ALL_COMPETENCIES = 'GET_ALL_COMPETENCIES'

/**
* Newsfeed
*/

export const GET_LOG_PROCCESSES_SAGA = 'GET_LOG_PROCCESSES'
export const GET_LOG_PROCCESSES_SUCCESS = 'GET_LOG_PROCCESSES_SUCCESS'
export const GET_LOG_PROCCESSES_FAILED = 'GET_LOG_PROCCESSES_FAILED'

/**
 * AnonymousFeedback
 */
export const LOADING_IN_ANONYMOUS_FEEDBACK = 'LOADING_IN_ANONYMOUS_FEEDBACK'

export const VERIFY_ANONYMOUS_URL_SAGA = 'VERIFY_ANONYMOUS_URL_SAGA'
export const VERIFY_ANONYMOUS_URL_SUCCESS = 'VERIFY_ANONYMOUS_URL_SUCCESS'
export const VERIFY_ANONYMOUS_URL_FAILURE = 'VERIFY_ANONYMOUS_URL_FAILURE'

export const GET_ANONYMOUS_QUESTION_SUCCESS = 'GET_ANONYMOUS_QUESTION_SUCCESS'
export const GET_ANONYMOUS_QUESTION_FAILURE = 'GET_ANONYMOUS_QUESTION_FAILURE'

export const SEND_ANONYMOUS_FEEDBACK_SAGA = 'SEND_ANONYMOUS_FEEDBACK_SAGA'
export const SEND_ANONYMOUS_FEEDBACK_SUCCESS = 'SEND_ANONYMOUS_FEEDBACK_SUCCESS'
export const SEND_ANONYMOUS_FEEDBACK_FAILURE = 'SEND_ANONYMOUS_FEEDBACK_FAILURE'

/**
 * Tracking
 */
export const LOADING_IN_TRACKING = 'LOADING_IN_TRACKING'

export const VERIFY_TRACKING_URL_SAGA = 'VERIFY_TRACKING_URL_SAGA'
export const VERIFY_TRACKING_URL_SUCCESS = 'VERIFY_TRACKING_URL_SUCCESS'
export const VERIFY_TRACKING_URL_FAILURE = 'VERIFY_TRACKING_URL_FAILURE'

export const SEND_TRACKING_URL_TO_EMAIL_SAGA = 'SEND_TRACKING_URL_TO_EMAIL_SAGA'
export const RATING_FEEDBACK_SAGA = 'RATING_FEEDBACK_SAGA'

/**
 * Feedback
 */
export const LOADING_IN_FEEDBACK = 'LOADING_IN_FEEDBACK'

export const GET_LIST_FEEDBACK_SUCCESS = 'GET_LIST_FEEDBACK_SUCCESS'
export const GET_LIST_FEEDBACK_FAILURE = 'GET_LIST_FEEDBACK_FAILURE'

export const GET_LINK_FEEDBACK_SAGA = 'GET_LINK_FEEDBACK_SAGA'
export const GET_LINK_FEEDBACK_SUCCESS = 'GET_LINK_FEEDBACK_SUCCESS'
export const GET_LINK_FEEDBACK_FAILURE = 'GET_LINK_FEEDBACK_FAILURE'

export const GET_ALL_FEEDBACK_PUBLIC_LOADING = 'GET_ALL_FEEDBACK_PUBLIC_LOADING'

export const GET_ALL_FEEDBACK_PUBLIC_STATS_SAGA = 'GET_ALL_FEEDBACK_PUBLIC_STATS_SAGA'
export const GET_ALL_FEEDBACK_PUBLIC_STATS_SUCCESS = 'GET_ALL_FEEDBACK_PUBLIC_STATS_SUCCESS'
export const GET_ALL_FEEDBACK_PUBLIC_STATS_FAILURE = 'GET_ALL_FEEDBACK_PUBLIC_STATS_FAILURE'
export const GET_ALL_FEEDBACK_PUBLIC_SAGA = 'GET_ALL_FEEDBACK_PUBLIC_SAGA'
export const GET_ALL_FEEDBACK_PUBLIC_SUCCESS = 'GET_ALL_FEEDBACK_PUBLIC_SUCCESS'
export const GET_ALL_FEEDBACK_PUBLIC_FAILURE = 'GET_ALL_FEEDBACK_PUBLIC_FAILURE'

export const GET_ALL_FEEDBACK_GIVE_STATS_SAGA = 'GET_ALL_FEEDBACK_GIVE_STATS_SAGA'
export const GET_ALL_FEEDBACK_GIVE_STATS_SUCCESS = 'GET_ALL_FEEDBACK_GIVE_STATS_SUCCESS'
export const GET_ALL_FEEDBACK_GIVE_STATS_FAILURE = 'GET_ALL_FEEDBACK_GIVE_STATS_FAILURE'
export const GET_ALL_FEEDBACK_GIVE_SAGA = 'GET_ALL_FEEDBACK_GIVE_SAGA'
export const GET_ALL_FEEDBACK_GIVE_SUCCESS = 'GET_ALL_FEEDBACK_GIVE_SUCCESS'
export const GET_ALL_FEEDBACK_GIVE_FAILURE = 'GET_ALL_FEEDBACK_GIVE_FAILURE'

export const GET_ALL_FEEDBACK_RECEIVED_STATS_SAGA = 'GET_ALL_FEEDBACK_RECEIVED_STATS_SAGA'
export const GET_ALL_FEEDBACK_RECEIVED_STATS_SUCCESS = 'GET_ALL_FEEDBACK_RECEIVED_STATS_SUCCESS'
export const GET_ALL_FEEDBACK_RECEIVED_STATS_FAILURE = 'GET_ALL_FEEDBACK_RECEIVED_STATS_FAILURE'
export const GET_ALL_FEEDBACK_RECEIVED_SAGA = 'GET_ALL_FEEDBACK_RECEIVED_SAGA'
export const GET_ALL_FEEDBACK_RECEIVED_SUCCESS = 'GET_ALL_FEEDBACK_RECEIVED_SUCCESS'
export const GET_ALL_FEEDBACK_RECEIVED_FAILURE = 'GET_ALL_FEEDBACK_RECEIVED_FAILURE'

export const VOTE_FOR_FEEDBACK_SAGA = 'VOTE_FOR_FEEDBACK_SAGA'
export const VOTE_FOR_FEEDBACK_SUCCESS = 'VOTE_FOR_FEEDBACK_SUCCESS'
export const VOTE_FOR_FEEDBACK_FAILURE = 'VOTE_FOR_FEEDBACK_FAILURE'

export const COMMENT_FEEDBACK_SAGA = 'COMMENT_FEEDBACK_SAGA'
export const COMMENT_FEEDBACK_LOADING = 'COMMENT_FEEDBACK_LOADING'
export const COMMENT_FEEDBACK_SUCCESS = 'COMMENT_FEEDBACK_SUCCESS'
export const COMMENT_FEEDBACK_FAILURE = 'COMMENT_FEEDBACK_FAILURE'

export const UPDATE_FEEDBACK_SAGA = 'UPDATE_FEEDBACK_SAGA'
export const UPDATE_FEEDBACK_LOADING = 'UPDATE_FEEDBACK_LOADING'
export const UPDATE_FEEDBACK_SUCCESS = 'UPDATE_FEEDBACK_SUCCESS'
export const UPDATE_FEEDBACK_FAILURE = 'UPDATE_FEEDBACK_FAILURE'

export const FETCHING_FEEDBACK = 'FETCHING_FEEDBACK'
export const FETCHING_FEEDBACK_FAILURE = 'FETCHING_FEEDBACK_FAILURE'

export const LOADING_IN_FEEDBACK_DISCUSSION = 'LOADING_IN_FEEDBACK_DISCUSSION'
export const GET_FEEDBACK_DISCUSSION_SAGA = 'GET_FEEDBACK_DISCUSSION_SAGA'
export const GET_FEEDBACK_DISCUSSION_SUCCESS = 'GET_FEEDBACK_DISCUSSION_SUCCESS'
export const GET_FEEDBACK_DISCUSSION_FAILURE = 'GET_FEEDBACK_DISCUSSION_FAILURE'

export const UPDATE_STATE_PUBLIC_ISSUE_SAGA = 'UPDATE_STATE_PUBLIC_ISSUE_SAGA'
export const UPDATE_STATE_PUBLIC_ISSUE_SUCCESS = 'UPDATE_STATE_PUBLIC_ISSUE_SUCCESS'
export const UPDATE_STATE_PUBLIC_ISSUE_FAILURE = 'UPDATE_STATE_PUBLIC_ISSUE_FAILURE'

/**
 * Bot
 */
export const LOADING_IN_BOT = 'LOADING_IN_BOT'

export const GET_QUESTION_REQUEST = 'GET_QUESTION_REQUEST'
export const GET_QUESTION_SUCCESS = 'GET_QUESTION_SUCCESS'
export const GET_QUESTION_FAILURE = 'GET_QUESTION_FAILURE'

export const SUBMIT_ISSUE_REQUEST = 'SUBMIT_ISSUE_REQUEST'

export const CLEAR_QUESTIONS = 'CLEAR_QUESTIONS'

/**
 * Chat Box
 */

export const GET_CHAT_BOX = 'GET_CHAT_BOX'
export const GET_CHAT_BOX_SUCCESS = 'GET_CHAT_BOX_SUCCESS'
export const SEND_CHAT_BOX = 'SEND_CHAT_BOX'

/**
 * Survey
 */

export const LOADING_IN_SURVEY = 'LOADING_IN_SURVEY'
export const LOADING_IN_SURVEY_STEP_1 = 'LOADING_IN_SURVEY_STEP_1'
export const LOADING_IN_SURVEY_STEP_2 = 'LOADING_IN_SURVEY_STEP_2'
export const GET_SURVEY_DETAIL_SAGA = 'GET_SURVEY_DETAIL_SAGA'
export const GET_SURVEY_DETAIL_SUCCESS = 'GET_SURVEY_DETAIL_SUCCESS'
export const GET_SURVEY_DETAIL_FAILURE = 'GET_SURVEY_DETAIL_FAILURE'
export const GET_ALL_SURVEY_TEMPLATE_SAGA = 'GET_ALL_SURVEY_TEMPLATE_SAGA'
export const GET_ALL_SURVEY_TEMPLATE_SUCCESS = 'GET_ALL_SURVEY_TEMPLATE_SUCCESS'
export const GET_ALL_SURVEY_TEMPLATE_FAILURE = 'GET_ALL_SURVEY_TEMPLATE_FAILURE'
export const GET_MY_CREATED_SURVEYS_SAGA = 'GET_MY_CREATED_SURVEYS_SAGA'
export const GET_MY_CREATED_SURVEYS_SUCCESS = 'GET_MY_CREATED_SURVEYS_SUCCESS'
export const GET_MY_CREATED_SURVEYS_FAILURE = 'GET_MY_CREATED_SURVEYS_FAILURE'
export const GET_MY_REQUESTED_SURVEYS_SAGA = 'GET_MY_REQUESTED_SURVEYS_SAGA'
export const GET_MY_REQUESTED_SURVEYS_SUCCESS = 'GET_MY_REQUESTED_SURVEYS_SUCCESS'
export const GET_MY_REQUESTED_SURVEYS_FAILURE = 'GET_MY_REQUESTED_SURVEYS_FAILURE'

export const SAVE_SURVEY_NEXT_STEP1_REQUEST = 'SAVE_SURVEY_NEXT_STEP1_REQUEST'
export const SAVE_SURVEY_NEXT_STEP1_SUCCESS = 'SAVE_SURVEY_NEXT_STEP1_SUCCESS'
export const SAVE_SURVEY_NEXT_STEP1_FAILURE = 'SAVE_SURVEY_NEXT_STEP1_FAILURE'

export const DELETE_SURVEY_REQUEST = 'DELETE_SURVEY_REQUEST'
export const DELETE_SURVEY_SUCCESS = 'DELETE_SURVEY_SUCCESS'
export const DELETE_SURVEY_FAILURE = 'DELETE_SURVEY_FAILURE'

export const LOCAL_UPDATE_SURVEY_TITLE = 'LOCAL_UPDATE_SURVEY_TITLE'
export const LOCAL_CREATE_SURVEY_QUESTION = 'LOCAL_CREATE_SURVEY_QUESTION'
export const LOCAL_UPDATE_SURVEY_QUESTION = 'LOCAL_UPDATE_SURVEY_QUESTION'
export const LOCAL_CREATE_SURVEY_QUESTION_ANSWER = 'LOCAL_CREATE_SURVEY_QUESTION_ANSWER'
export const LOCAL_UPDATE_SURVEY_QUESTION_ANSWER = 'LOCAL_UPDATE_SURVEY_QUESTION_ANSWER'
export const LOCAL_DELETE_SURVEY_QUESTION_ANSWER = 'LOCAL_DELETE_SURVEY_QUESTION_ANSWER'

export const CLEAR_SURVEY_EDIT = 'CLEAR_SURVEY_EDIT'

/**
 * Question types
 */

export const GET_QUESTION_TYPES = 'GET_QUESTION_TYPES'
export const GET_QUESTION_TYPES_LOADING = 'GET_QUESTION_TYPES_LOADING'
export const GET_QUESTION_TYPES_SUCCESS = 'GET_QUESTION_TYPES_SUCCESS'
export const GET_QUESTION_TYPES_FAILURE = 'GET_QUESTION_TYPES_FAILURE'

export const UPDATE_SURVEY_QUESTION = 'UPDATE_SURVEY_QUESTION'
export const UPDATE_SURVEY_QUESTION_SUCCESS = 'UPDATE_SURVEY_QUESTION_SUCCESS'
export const UPDATE_SURVEY_QUESTION_FAILURE = 'UPDATE_SURVEY_QUESTION_FAILURE'
export const UPDATE_SURVEY_QUESTION_ANSWER = 'UPDATE_SURVEY_QUESTION_ANSWER'
export const CREATE_SURVEY_QUESTION = 'CREATE_SURVEY_QUESTION'
export const CREATE_SURVEY_QUESTION_SUCCESS = 'CREATE_SURVEY_QUESTION_SUCCESS'
export const CREATE_SURVEY_QUESTION_FAILURE = 'CREATE_SURVEY_QUESTION_FAILURE'

export const SUBMIT_SURVEY_SETTING = 'SUBMIT_SURVEY_SETTING'
export const SUBMIT_SURVEY_SETTING_LOADING = 'SUBMIT_SURVEY_SETTING_LOADING'
export const SUBMIT_SURVEY_SETTING_SUCCESS = 'SUBMIT_SURVEY_SETTING_SUCCESS'
export const SUBMIT_SURVEY_SETTING_FAILURE = 'SUBMIT_SURVEY_SETTING_FAILURE'

export const PUBLISH_SURVEY = 'PUBLISH_SURVEY'
export const PUBLISH_SURVEY_SUCCESS = 'PUBLISH_SURVEY_SUCCESS'
export const PUBLISH_SURVEY_FAILURE = 'PUBLISH_SURVEY_FAILURE'

export const UPDATE_SCHEDULE_REQUEST = 'UPDATE_SCHEDULE_REQUEST'
export const UPDATE_SCHEDULE_SUCCESS = 'UPDATE_SCHEDULE_SUCCESS'
export const UPDATE_SCHEDULE_FAILURE = 'UPDATE_SCHEDULE_FAILURE'

